### ISSUE TITLE
Speaker photo upload: Opan Mustopah

### ISSUE THREAD

**Issue by opan** [id-ruby/id-ruby#114]
Hi, based on the instruction in the email, I was told to create an issue on id-ruby website repository. How can I add my profile pic?

Thanks

**Comment by firewalker06** [comment]
Just include the URL to your profile picture in this issue 😊

**Comment by opan** [comment]
Here is the link mas:

https://drive.google.com/file/d/18lOccwiMEqmRR8_--8UEZmxKvoN_w2om/view?usp=sharing

Please let me know if you still can't access the image

Thanks
