### ISSUE TITLE
When is the next RubyConf ID?

### ISSUE THREAD

**Issue by empeje** [id-ruby/id-ruby#134]
Hi Team,

I'm an active Ruby user and use it for both work and side-hustles. Is there any plan for the upcoming RubyConf ID?

**Comment by giosakti** [comment]
Hi,

No plan as of now.. In face we are looking into volunteers whom can help co-organize the community activity itself. Let me know if you are interested.

cc @waruboy @firewalker06

**Comment by empeje** [comment]
Ah noted.

Is Slack still active? I have a tech-community team in our company who would like to volunteer. I can chat with you over Slack.

**Comment by giosakti** [comment]
No, I think the slack is inactive
we can use discord that we setup sometimes back https://discord.gg/kP5qNa24

the main community is telegram, but too many members over there so it may be more conducive to discuss in discord instead
