### ISSUE TITLE
[Meetup Request] Let's have a meetup about Testing in Jakarta

### ISSUE THREAD

**Issue by firewalker06** [id-ruby/id-ruby#79]
- [ ] When: October 2018
- [ ] Where: No plan yet (suggestions welcomed, anywhere in Jakarta)
- [ ] Who will presents:
  - @mufid (TBD)
  - Abdullah (TBD)

## Background

Its been a while since our [last meetup](https://www.meetup.com/id-ruby/events/251979153/). As an organizer, I believe we can conduct more frequent meetups by opening the organizing process to public. To get more minds into creating interesting meetup experience.

To begin the first [Meetup Request], @mufid wants to conduct a survey about software testing 👏. I suggested he make a talk out of it, then do the survey with the audience. Our kind Abdullah offered his 20 min talk about property based testing 🙇.

## What you can do to help?

- if you are interested to attend this meetup, please give :+1:
- please leave a comment if you want to:
  - give a talk
  - suggest meetup venue
- spread news about this issue
- join our `#volunteers` Slack channel at http://ruby.id/slack to discuss other ways to help

**Comment by mufid** [comment]
Hi. We are from [AgileCampus](https://twitter.com/agilecampus) want to share our newest product to make people easier to test their own web application. Usually this is done by signing up to Browserstack or by building your own BDD test by using Capybara. In our talk, we will show you how to build your own test stack with Gherkin/Capybara and how our new product can simplify your BDD test!

Should there anything AgileCampus can help, please kindly ping me via this Github issue.

**Comment by firewalker06** [comment]
Closing this issue since we have no update until December 😥

Please open new issue if you have new plan @mufid 🙇
