### ISSUE TITLE
[Meetup Request] Let's have a meetup in Yogya!

### ISSUE THREAD

**Issue by firewalker06** [id-ruby/id-ruby#80]
- [x] When: November 19, 2018 18:00
- [x] Where: Sevensky
- [x] What to discuss: introduce yourself, share your Ruby experience

## Background

@agungsetiawan and @SunDi3yansyah would like to host our meetup in Yogya! They have the place ready and only need one more volunteer to speak in the meetup 😃. There is no theme for this meetup, so feel free to submit any topic involving Ruby or programming in general 🎉.

## What you can do to help?

- if you are interested to attend this meetup, please give :+1:
- please leave a comment if you want to give a talk
- spread news about this issue
- join our `#volunteers` Slack channel at http://ruby.id/slack to discuss other ways to help

**Comment by SunDi3yansyah** [comment]
### [UPDATE: Meetup]

Ngopi bareng anak gaul insinyur bahasa Ruby

:gem: Di Sevensky
:gem: Tanggal 19 November 2018, hari Senin pukul 18.00 (malam selasa) sampai selesai
:gem: Topiknya apaan? Ngobrol santai, perkenalan, menjelaskan pengalaman pribadi

Harap yang di daerah seputar Jogja bisa datang :ok_hand:

**Comment by firewalker06** [comment]
@SunDi3yansyah awesome :+1:

**Comment by waruboy** [comment]
ditunggu foto2nya yaa
