### ISSUE TITLE
[Meetup Request] Let's have a meetup about Ruby Performance in Jakarta!

### ISSUE THREAD

**Issue by firewalker06** [id-ruby/id-ruby#83]
- [x] When: Sometime in January
- [x] Where: TBA
- [x] What to discuss: 
    - @giosakti: Why people are saying ruby is slow and why it isn't relevan 90% of the time?  
    - @waruboy: Day to day Rails performance tips 
    - @firewalker06: What's new in Ruby 2.6 in terms of performance?  

## Background

Starting up 2019 with Ruby Performance!

## What you can do to help?

- if you are interested to attend this meetup, please give :+1:
- share about this meetup in your social media channels
- join our `#volunteers` Slack channel at http://ruby.id/slack to discuss other ways to help
- feel free to leave a comment if you want to give a talk at the next meetup

**Comment by giosakti** [comment]
held in GO-JEK by the end of january
https://www.meetup.com/id-ruby/events/258108712/
